management:
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 1m
        enabled: true
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  health:
    rabbit:
      enabled: false


