app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    validity-in-ms: P7D
  recapture:
    secret-key: ${RECAPTURE_SECRET_KEY}

spring:
  application:
    name: pmlite-api
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog.master.xml
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

server:
  error:
    include-message: always

#logging:
#  level:
#    org.springframework.security: DEBUG
