app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    validity-in-ms: P365D
  recaptcha:
    default:
      secret-key: ${DEFAULT_RECAPTCHA_SECRET_KEY}
    invisible:
      secret-key: ${INVISIBLE_RECAPTCHA_SECRET_KEY}
  website:
    url: ${WEBSITE_URL}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    user: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

spring:
  application:
    name: pmlite-api
  task:
    execution:
      pool:
        max-size: 16
  liquibase:
    change-log: classpath:db/changelog/db.changelog.master.xml
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  mail:
    host: smtp.mail.ru
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connection-timeout: 5000
          ssl.trust: smtp.mail.ru
          starttls.enable: true
          timeout: 3000
          write-timeout: 5000
        transport.protocol: smtp
    default-encoding: UTF-8
  profiles:
    active:

server:
  error:
    include-message: always
    include-stacktrace: never

management:
  health:
    rabbit:
      enabled: false
  otlp:
    metrics:
      export:
        enabled: false
